[publy]
title = "퍼블리"
url = "https://publy.co/topic/all?fr=top-navi"
entrySelector = "div.row div.col-4.mb-9"
titleSelector = "h6.text-gray-900.font-weight-normal.font-size-medium.text-truncate-2.leading-tight.mb-0"
linkSelector = "a.d-block.position-relative"
contentSelector = "p.font-size-xsmall.text-gray-600"
waitUntil = "networkidle"
onFail = "stale"

[careet]
title = "캐릿"
url = "https://www.careet.net/Content/All"
entrySelector = "ul.list-wrap.gly-list.col3 li"
titleSelector = "p.list-tit"
linkSelector = "a"
contentSelector = "p.txt-elp.list-desc"
imageSelector = "div.list-thumb img.thumb-img"
waitUntil = "networkidle"
onFail = "stale"

[longblack]
title = "롱블랙"
url = "https://www.longblack.co/"
entrySelector = "div[id='main-today-note']"
titleSelector = "h2.today-note-title"
linkSelector = "a"
contentSelector = "p.today-note-desc"
imageSelector = "div.bg-img.ratio-4-3"
waitUntil = "networkidle"
onFail = "stale"

[folin]
title = "폴인"
url = "https://www.folin.co/story"
entrySelector = "//html/body/div[1]/div/article/section[2]/div/div/div[1]/ul/li"
titleSelector = "//a/div/h3"
linkSelector = "//a"
contentSelector = "//a/div[2]/ul[1]"
waitUntil = "networkidle"
onFail = "stale"

[bookjournalism]
title = "북저널리즘"
url = "https://www.bookjournalism.com/books"
entrySelector = "div.item"
titleSelector = "span.summary"
linkSelector = "a.link-inner"
contentSelector = "span.post-title"
imageSelector = "span.cover"
waitUntil = "networkidle"
onFail = "stale"

[naver_premium_free]
title = "네이버 프리미엄콘텐츠 ─ 무료 프로모션"
url = "https://contents.premium.naver.com/"
entrySelector = "ul.promotion_list._PROMOTION_LIST li.promotion_item"
titleSelector = "strong.promotion_title"
linkSelector = "div a.promotion_link_2"
contentSelector = "p.promotion_info"
imageSelector = "div.promotion_img_area img._LAZY_LOADING"
waitUntil = "networkidle"
onFail = "stale"
